# -*- coding: utf-8 -*-
INSTRUMENTS = (
    (1, 'Violín'),
    (2, 'Viola'),
    (3, 'Violonchelo'),
    (4, 'Bajo'),
    (5, 'Contrabajo'),
    (6, 'Arpa'),
    (7, 'Guitarra'),
    (8, 'Clavicémbalo'),
    (9, 'Piano'),
    (10, 'Organo'),
    (11, 'Flauta'),
    (12, 'Flautín'),
    (13, 'Clarinete Alto'),
    (14, 'Clarinete Bajo'),
    (15, 'Oboe'),
    (16, 'Corno Inglés'),
    (17, 'Fagot'),
    (18, 'Contrafagot'),
    (19, 'Trompeta'),
    (20, 'Tuba'),
    (21, 'Saxofón'),
    (22, 'Timbal'),
    (23, 'Xilófon'),
    (24, 'Celesta'),
    (25, 'Campanas Tubulares'),
    (26, 'Bombo'),
    (27, 'Caja'),
    (28, 'Platillos'),
    (29, 'Castañuelas'),
    (30, 'Bateria'),
    (31, 'Vocal'),
    (32, 'otros'),
)

